### ISSUE TITLE
Logo proposal for ansible role openvas

### ISSUE THREAD

**Issue by candyskull920** [robertdebock/ansible-role-openvas#1]
Hi @robertdebock 
I am an open source enthusiast and I am looking to expand my work portfolio.
I would like to collaborate with your project for free, I can provide you with a logo for your project

Good day
Skull C.

**Comment by robertdebock** [comment]
Wow, that's really cool!

I'm looking for a logo for [many roles](https://robertdebock.nl). Would that be something you could help with?

**Comment by candyskull920** [comment]
Hi @robertdebock 
Of course, gladly, if you could tell me what the project is exactly about and if you want the logo:
transmit something specific
some specific color
let me know so that the logo is as accurate as possible.

Skull C.

**Comment by robertdebock** [comment]
Cool. These Ansible roles should make it easier for system administrators to build a server.

I see these roles as building blocks, like lego or bricks.

The quality of these roles is that they are:
- simple
- small/minimal
- composable.

Color; maybe black/white, because that also quite minimal.

Once agian, thanks!

**Comment by candyskull920** [comment]
hi @robertdebock 
Soon I will be uploading my proposal.

**Comment by blaisep** [comment]
Hi @candyskull920 , if you are still working on the logos, consider taking a look at the fedora patternfly project: https://www.patternfly.org/styles/ 
There may be some useful ideas or references there for you.

**Comment by robertdebock** [comment]
I'm going to close this issue because of inactivity.
