### ISSUE TITLE
OpenVAS Error 503

### ISSUE THREAD

**Issue by deepsarrow** [robertdebock/ansible-role-openvas#3]
Hey Guys

I am attempting to start openvas but it shows the below error. The GUI internface in browser opens but no commands run on it. It shows 503 error. Guys Please help

Thanks in Advance

root@Deeps:~# openvas-start
[*] Please wait for the OpenVAS services to start.
[*]
[*] You might need to refresh your browser once it opens.
[*]
[*]  Web UI (Greenbone Security Assistant): https://127.0.0.1:9392

Job for openvas-scanner.service failed because a timeout was exceeded.
See "systemctl status openvas-scanner.service" and "journalctl -xe" for details.
● greenbone-security-assistant.service - Greenbone Security Assistant
   Loaded: loaded (/lib/systemd/system/greenbone-security-assistant.service; disabled; vendor preset: disabled)
   Active: active (running) since Fri 2019-01-11 13:03:07 IST; 1min 35s ago
     Docs: man:gsad(8)
           http://www.openvas.org/
 Main PID: 2439 (gsad)
    Tasks: 4 (limit: 4915)
   Memory: 3.8M
   CGroup: /system.slice/greenbone-security-assistant.service
           ├─2439 /usr/sbin/gsad --foreground --listen=127.0.0.1 --port=9392 --mlisten=127.0.0.1 --mport=9390
           └─2443 /usr/sbin/gsad --foreground --listen=127.0.0.1 --port=9392 --mlisten=127.0.0.1 --mport=9390

Jan 11 13:03:07 Deeps systemd[1]: Started Greenbone Security Assistant.
Jan 11 13:03:07 Deeps gsad[2439]: Warning: MHD_USE_THREAD_PER_CONNECTION must be used only with MHD_USE_INTERNAL_POLLING_THREAD. Flag MHD_USE_INTERNAL_POLLING_THREAD was added. Consider setting MHD_USE_INTERNAL_POLLING_THREAD explicitly.
Jan 11 13:03:07 Deeps gsad[2439]: Warning: MHD_USE_THREAD_PER_CONNECTION must be used only with MHD_USE_INTERNAL_POLLING_THREAD. Flag MHD_USE_INTERNAL_POLLING_THREAD was added. Consider setting MHD_USE_INTERNAL_POLLING_THREAD explicitly.

● openvas-scanner.service - Open Vulnerability Assessment System Scanner Daemon
   Loaded: loaded (/lib/systemd/system/openvas-scanner.service; disabled; vendor preset: disabled)
   Active: failed (Result: timeout) since Fri 2019-01-11 13:04:38 IST; 5s ago
     Docs: man:openvassd(8)
           http://www.openvas.org/
  Process: 2450 ExecStart=/usr/sbin/openvassd --unix-socket=/var/run/openvassd.sock (code=killed, signal=TERM)

Jan 11 13:03:08 Deeps systemd[1]: Starting Open Vulnerability Assessment System Scanner Daemon...
Jan 11 13:04:38 Deeps systemd[1]: openvas-scanner.service: Start operation timed out. Terminating.
Jan 11 13:04:38 Deeps systemd[1]: openvas-scanner.service: Failed with result 'timeout'.
Jan 11 13:04:38 Deeps systemd[1]: Failed to start Open Vulnerability Assessment System Scanner Daemon.

● openvas-manager.service - Open Vulnerability Assessment System Manager Daemon
   Loaded: loaded (/lib/systemd/system/openvas-manager.service; disabled; vendor preset: disabled)
   Active: active (running) since Fri 2019-01-11 13:03:10 IST; 1min 33s ago
     Docs: man:openvasmd(8)
           http://www.openvas.org/
  Process: 2440 ExecStart=/usr/sbin/openvasmd --listen=127.0.0.1 --port=9390 --database=/var/lib/openvas/mgr/tasks.db (code=exited, status=0/SUCCESS)
 Main PID: 2442 (openvasmd)
    Tasks: 1 (limit: 4915)
   Memory: 169.1M
   CGroup: /system.slice/openvas-manager.service
           └─2442 openvasmd

Jan 11 13:03:07 Deeps systemd[1]: Starting Open Vulnerability Assessment System Manager Daemon...
Jan 11 13:03:07 Deeps systemd[1]: openvas-manager.service: Can't open PID file /var/run/openvasmd.pid (yet?) after start: No such file or directory
Jan 11 13:03:10 Deeps systemd[1]: Started Open Vulnerability Assessment System Manager Daemon.

[*] Opening Web UI (https://127.0.0.1:9392) in: 5... 4... 3... 2... 1... 
root@Deeps:~# systemctl status openvas-scanner.service
● openvas-scanner.service - Open Vulnerability Assessment System Scanner Daemon
   Loaded: loaded (/lib/systemd/system/openvas-scanner.service; disabled; vendor preset: disabled)
   Active: failed (Result: timeout) since Fri 2019-01-11 13:04:38 IST; 42s ago
     Docs: man:openvassd(8)
           http://www.openvas.org/
  Process: 2450 ExecStart=/usr/sbin/openvassd --unix-socket=/var/run/openvassd.sock (code=killed, signal=TERM)

Jan 11 13:03:08 Deeps systemd[1]: Starting Open Vulnerability Assessment System Scanner Daemon...
Jan 11 13:04:38 Deeps systemd[1]: openvas-scanner.service: Start operation timed out. Terminating.
Jan 11 13:04:38 Deeps systemd[1]: openvas-scanner.service: Failed with result 'timeout'.
Jan 11 13:04:38 Deeps systemd[1]: Failed to start Open Vulnerability Assessment System Scanner Daemon.
root@Deeps:~# journalctl -xe
Jan 11 13:03:07 Deeps gsad[2439]: Warning: MHD_USE_THREAD_PER_CONNECTION must be used only with MHD_USE_INTERNAL_POLLING_THREAD. Flag MHD_USE_INTERNAL
Jan 11 13:03:08 Deeps systemd[1]: redis-server@openvas.service: Can't open PID file /run/redis-openvas/redis-server.pid (yet?) after start: No such fi
Jan 11 13:03:08 Deeps systemd[1]: Started Advanced key-value store (openvas).
-- Subject: Unit redis-server@openvas.service has finished start-up
-- Defined-By: systemd
-- Support: https://www.debian.org/support
-- 
-- Unit redis-server@openvas.service has finished starting up.
-- 
-- The start-up result is RESULT.
Jan 11 13:03:08 Deeps systemd[1]: Starting Open Vulnerability Assessment System Scanner Daemon...
-- Subject: Unit openvas-scanner.service has begun start-up
-- Defined-By: systemd
-- Support: https://www.debian.org/support
-- 
-- Unit openvas-scanner.service has begun starting up.
Jan 11 13:03:10 Deeps systemd[1]: Started Open Vulnerability Assessment System Manager Daemon.
-- Subject: Unit openvas-manager.service has finished start-up
-- Defined-By: systemd
-- Support: https://www.debian.org/support
-- 
-- Unit openvas-manager.service has finished starting up.
-- 
-- The start-up result is RESULT.
Jan 11 13:04:38 Deeps systemd[1]: openvas-scanner.service: Start operation timed out. Terminating.
Jan 11 13:04:38 Deeps systemd[1]: openvas-scanner.service: Failed with result 'timeout'.
Jan 11 13:04:38 Deeps systemd[1]: Failed to start Open Vulnerability Assessment System Scanner Daemon.
-- Subject: Unit openvas-scanner.service has failed
-- Defined-By: systemd
-- Support: https://www.debian.org/support
-- 
-- Unit openvas-scanner.service has failed.
-- 
-- The result is RESULT.
Jan 11 13:05:01 Deeps CRON[2650]: pam_unix(cron:session): session opened for user root by (uid=0)
Jan 11 13:05:01 Deeps CRON[2651]: (root) CMD (command -v debian-sa1 > /dev/null && debian-sa1 1 1)
Jan 11 13:05:01 Deeps CRON[2650]: pam_unix(cron:session): session closed for user root

**Comment by robertdebock** [comment]
I'll have a look, thanks for the error report.

**Comment by robertdebock** [comment]
Are you sure you are using this Ansible role to deploy openvas? I don't see any reference to it in your output.

Please let me know what commands (`ansible-playbook ...`) you ran on what type of machine and what the output was of the playbook.

**Comment by deepsarrow** [comment]
First Thank you robert for replying. I have been trying to run this on my Kali Linux Laptop having Dual Boot. The said service was working fine but it got interrupted due to some network issue now the same is failing to start. I have searched on various other forums and I have found that the .socket file has that error. So if you can suggest me the type of file required to open it, that also might lead me to solving the error

**Comment by deepsarrow** [comment]
First Thank you robert for replying. I have been trying to run this on my Kali Linux Laptop having Dual Boot. The said service was working fine but it got interrupted due to some network issue now the same is failing to start. I have searched on various other forums and I have found that the .socket file has that error. So if you can suggest me the type of file required to open it, that also might lead me to solving the error

**Comment by robertdebock** [comment]
Ah, okay. Well, I'm not an expert on openvas either, I just like to write these Ansible roles to install and configure stuff, like openvas.

I would search and possibly ask the question on [this forum](https://forums.atomicorp.com/viewforum.php?f=31), see if anybody else experienced that issue before.
